CP-41983: Update iperf2 to 3
xenserver/auto-cert-kit pull request #202
Opened 2023-04-28 06:20 UTC by tianxiahcp

2023-05-02 09:32 UTC, lindig commented
This needs a better commit message including a sign-off.

2023-05-02 09:36 UTC, lindig requested changes

2023-05-02 09:36 UTC, lindig commented on setup-scripts/init-run.sh
> +# open port for iperf3
Port numbers change. This should go into the commit message and probably into documentation. Does this need discussion?

2023-05-06 03:29 UTC, DeliZhangX commented on autocertkit/network_tests.py
> -        rec['bandwidth'] = arr[8]
`bandwidth` is useful, should keep it and I saw iperf3 still support it from https://iperf.fr/iperf-doc.php

2023-05-06 03:29 UTC, DeliZhangX commented on autocertkit/network_tests.py
> +        cmd_str = "iperf -J %s %s -B %s -c %s" % \
Should consider to run `iperf3` if applied.

2023-05-06 03:31 UTC, DeliZhangX commented
@catherineliuchina You could submit new PR with fixes as Tian Xia left XS.

2024-03-07 06:56 UTC, closed without merging